"""String enums persisted to the database (stored as plain strings for portability)."""

from __future__ import annotations

from enum import StrEnum


class AssetStatus(StrEnum):
    ACTIVE = "ASSET_STATUS_ACTIVE"
    INACTIVE = "ASSET_STATUS_INACTIVE"
    UNSPECIFIED = "ASSET_STATUS_UNSPECIFIED"


class StrategyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    WATCH = "WATCH"
    DISABLED = "DISABLED"


class Side(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class FillKind(StrEnum):
    """How a strategy's virtual position changed. Only ONCHAIN_EXECUTION touched the chain."""

    INTERNAL_CROSS = "INTERNAL_CROSS"
    ONCHAIN_EXECUTION = "ONCHAIN_EXECUTION"
    DRY_RUN = "DRY_RUN"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    QUOTED = "QUOTED"
    VALIDATED = "VALIDATED"
    SUBMITTED = "SUBMITTED"
    CONFIRMED = "CONFIRMED"
    DRY_RUN_FILLED = "DRY_RUN_FILLED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class ExecutionMode(StrEnum):
    DRY_RUN = "DRY_RUN"
    LIVE = "LIVE"


class TxStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    REVERTED = "REVERTED"
    DROPPED = "DROPPED"


class TxKind(StrEnum):
    SWAP = "SWAP"
    APPROVE = "APPROVE"
    WITHDRAWAL = "WITHDRAWAL"


class FundingKind(StrEnum):
    BASE_CAPITAL = "BASE_CAPITAL"
    CONTRIBUTION = "CONTRIBUTION"
    DEMO_SEED = "DEMO_SEED"


class CycleStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReconciliationStatus(StrEnum):
    OK = "RECONCILIATION_OK"
    FAILED = "RECONCILIATION_FAILED"


class EventType(StrEnum):
    MARKET_DATA_UPDATED = "MARKET_DATA_UPDATED"
    UNIVERSE_UPDATED = "UNIVERSE_UPDATED"
    ASSET_REMOVED = "ASSET_REMOVED"
    STRATEGY_CYCLE_STARTED = "STRATEGY_CYCLE_STARTED"
    STRATEGY_CYCLE_COMPLETED = "STRATEGY_CYCLE_COMPLETED"
    STRATEGY_CYCLE_FAILED = "STRATEGY_CYCLE_FAILED"
    STRATEGY_SIGNAL_CREATED = "STRATEGY_SIGNAL_CREATED"
    STRATEGY_STATUS_CHANGED = "STRATEGY_STATUS_CHANGED"
    TARGETS_AGGREGATED = "TARGETS_AGGREGATED"
    RISK_LIMIT_APPLIED = "RISK_LIMIT_APPLIED"
    INTERNAL_CROSS = "INTERNAL_CROSS"
    QUOTE_RECEIVED = "QUOTE_RECEIVED"
    QUOTE_REJECTED = "QUOTE_REJECTED"
    ORDER_REJECTED = "ORDER_REJECTED"
    EXECUTION_SUBMITTED = "EXECUTION_SUBMITTED"
    EXECUTION_CONFIRMED = "EXECUTION_CONFIRMED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_DRY_RUN = "EXECUTION_DRY_RUN"
    TREASURY_UPDATED = "TREASURY_UPDATED"
    FUNDING_RECEIVED = "FUNDING_RECEIVED"
    WITHDRAWAL_RECORDED = "WITHDRAWAL_RECORDED"
    RECONCILIATION_OK = "RECONCILIATION_OK"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    SYSTEM_PAUSED = "SYSTEM_PAUSED"
    SYSTEM_RESUMED = "SYSTEM_RESUMED"
    SYSTEM_STARTED = "SYSTEM_STARTED"
    CONFIG_WARNING = "CONFIG_WARNING"


class EventLevel(StrEnum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
