"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-18 18:52:40.748145
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("rh_asset_id", sa.String(length=128), nullable=True),
        sa.Column("isin", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_multiplier", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("pending_multiplier", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("pending_multiplier_effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fractional_tradability", sa.Boolean(), nullable=False),
        sa.Column("all_day_tradability", sa.Boolean(), nullable=False),
        sa.Column("extended_hours_fractional_tradability", sa.Boolean(), nullable=False),
        sa.Column("is_halted", sa.Boolean(), nullable=False),
        sa.Column("in_allowlist", sa.Boolean(), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("eligibility_reasons", sa.JSON(), nullable=False),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=True)
    op.create_table(
        "cycles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nav_at_start", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cycles_session_date"), "cycles", ["session_date"], unique=False)
    op.create_table(
        "funding_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("asset_symbol", sa.String(length=16), nullable=False),
        sa.Column("tx_hash", sa.String(length=66), nullable=True),
        sa.Column("from_address", sa.String(length=42), nullable=True),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("allocated", sa.Boolean(), nullable=False),
        sa.Column("allocation", sa.JSON(), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "historical_bars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("high", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("low", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("close", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("volume", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "provider", "session_date", name="uq_bar_symbol_provider_date"
        ),
    )
    op.create_index(
        "ix_bars_symbol_date", "historical_bars", ["symbol", "session_date"], unique=False
    )
    op.create_table(
        "reconciliation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tolerance_bps", sa.Integer(), nullable=False),
        sa.Column("max_break_bps", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cash_break", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("position_breaks", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("triggered_pause", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_events_run_at"), "reconciliation_events", ["run_at"], unique=False
    )
    op.create_table(
        "simulated_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_reason", sa.String(length=256), nullable=True),
        sa.Column("current_version_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strategies_code"), "strategies", ["code"], unique=True)
    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_created", "system_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_system_events_type"), "system_events", ["type"], unique=False)
    op.create_table(
        "system_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("pause_reason", sa.String(length=256), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failed_txs", sa.Integer(), nullable=False),
        sa.Column("last_cycle_id", sa.Integer(), nullable=True),
        sa.Column("last_cycle_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_cycle_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reconciliation_status", sa.String(length=32), nullable=True),
        sa.Column("last_reconciliation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_market_data_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_universe_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("turnover_date", sa.Date(), nullable=True),
        sa.Column("turnover_notional", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("bootstrapped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treasury_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=True),
        sa.Column("nav", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("positions_value", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("deployable_capital", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("reserved_cash", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("gas_balance_eth", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("gas_balance_usd", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("cumulative_gas_eth", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("cumulative_gas_usd", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("base_capital", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("contributions_total", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("withdrawals_total", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("twr_index", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_treasury_snapshots_taken_at"), "treasury_snapshots", ["taken_at"], unique=False
    )
    op.create_table(
        "withdrawal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("asset_symbol", sa.String(length=16), nullable=False),
        sa.Column("to_address", sa.String(length=42), nullable=True),
        sa.Column("tx_hash", sa.String(length=66), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_by", sa.String(length=64), nullable=False),
        sa.Column("deallocation", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("contract_address", sa.String(length=42), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("verified_onchain", sa.Boolean(), nullable=False),
        sa.Column("onchain_multiplier", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "chain_id", name="uq_asset_chain"),
    )
    op.create_index(
        op.f("ix_asset_deployments_asset_id"), "asset_deployments", ["asset_id"], unique=False
    )
    op.create_table(
        "execution_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("local_id", sa.String(length=32), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("requested_notional", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("quoted_quantity", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("quoted_notional", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("executed_quantity", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("executed_notional", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("reference_price", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("expected_price", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("effective_price", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("slippage_bps", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("price_impact_bps", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("gas_used", sa.Integer(), nullable=True),
        sa.Column("gas_cost_eth", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("gas_cost_usd", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["cycles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("local_id"),
    )
    op.create_index(
        op.f("ix_execution_orders_cycle_id"), "execution_orders", ["cycle_id"], unique=False
    )
    op.create_table(
        "internal_crosses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("buyer_strategy_id", sa.Integer(), nullable=False),
        sa.Column("seller_strategy_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("price", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("notional", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("reference_price_source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["buyer_strategy_id"],
            ["strategies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_internal_crosses_cycle_id"), "internal_crosses", ["cycle_id"], unique=False
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("nav", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("cash", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("positions_value", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("allocated_capital", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("drawdown_pct", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("twr_index", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_psnap_strategy_taken", "portfolio_snapshots", ["strategy_id", "taken_at"], unique=False
    )
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("bid", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("ask", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("mid", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("daily_volume", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("is_halted", sa.Boolean(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_asset_fetched", "price_snapshots", ["asset_id", "fetched_at"], unique=False
    )
    op.create_table(
        "strategy_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("weight_pct", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("policy", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_allocations_strategy_id"),
        "strategy_allocations",
        ["strategy_id"],
        unique=False,
    )
    op.create_table(
        "strategy_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("last_price", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("market_value", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id", "asset_id", name="uq_strategy_asset"),
    )
    op.create_index(
        op.f("ix_strategy_positions_asset_id"), "strategy_positions", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_positions_strategy_id"),
        "strategy_positions",
        ["strategy_id"],
        unique=False,
    )
    op.create_table(
        "strategy_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("target_weight", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("previous_weight", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signals_strategy_created",
        "strategy_signals",
        ["strategy_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_signals_cycle_id"), "strategy_signals", ["cycle_id"], unique=False
    )
    op.create_table(
        "strategy_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("virtual_cash", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("allocated_capital", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("current_nav", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("peak_nav", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("max_drawdown_pct", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("current_drawdown_pct", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cumulative_turnover", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("signals_count", sa.Integer(), nullable=False),
        sa.Column("fills_count", sa.Integer(), nullable=False),
        sa.Column("twr_index", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("last_cycle_id", sa.Integer(), nullable=True),
        sa.Column("last_rebalance_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inception_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id"),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id", "version_hash", name="uq_strategy_version"),
    )
    op.create_index(
        op.f("ix_strategy_versions_strategy_id"), "strategy_versions", ["strategy_id"], unique=False
    )
    op.create_table(
        "blockchain_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sa.String(length=66), nullable=False),
        sa.Column("from_address", sa.String(length=42), nullable=False),
        sa.Column("to_address", sa.String(length=42), nullable=False),
        sa.Column("nonce", sa.Integer(), nullable=True),
        sa.Column("gas_limit", sa.Integer(), nullable=True),
        sa.Column("gas_used", sa.Integer(), nullable=True),
        sa.Column("effective_gas_price_wei", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("gas_cost_eth", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("gas_cost_usd", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["execution_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tx_hash"),
    )
    op.create_index(
        op.f("ix_blockchain_transactions_order_id"),
        "blockchain_transactions",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "execution_quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("sell_token", sa.String(length=42), nullable=False),
        sa.Column("buy_token", sa.String(length=42), nullable=False),
        sa.Column("sell_amount", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("buy_amount", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("min_buy_amount", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("price", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("price_impact_bps", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("gas_estimate", sa.Integer(), nullable=True),
        sa.Column("gas_price_wei", sa.Numeric(precision=40, scale=18), nullable=True),
        sa.Column("allowance_spender", sa.String(length=42), nullable=True),
        sa.Column("allowance_required", sa.Boolean(), nullable=False),
        sa.Column("liquidity_available", sa.Boolean(), nullable=False),
        sa.Column("route", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["execution_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_quotes_order_id"), "execution_quotes", ["order_id"], unique=False
    )
    op.create_table(
        "virtual_fills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("price", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("notional", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=40, scale=18), nullable=False),
        sa.Column("internal_cross_id", sa.Integer(), nullable=True),
        sa.Column("execution_order_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_order_id"],
            ["execution_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["internal_cross_id"],
            ["internal_crosses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fills_strategy_created", "virtual_fills", ["strategy_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_virtual_fills_cycle_id"), "virtual_fills", ["cycle_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_fills_cycle_id"), table_name="virtual_fills")
    op.drop_index("ix_fills_strategy_created", table_name="virtual_fills")
    op.drop_table("virtual_fills")
    op.drop_index(op.f("ix_execution_quotes_order_id"), table_name="execution_quotes")
    op.drop_table("execution_quotes")
    op.drop_index(op.f("ix_blockchain_transactions_order_id"), table_name="blockchain_transactions")
    op.drop_table("blockchain_transactions")
    op.drop_index(op.f("ix_strategy_versions_strategy_id"), table_name="strategy_versions")
    op.drop_table("strategy_versions")
    op.drop_table("strategy_states")
    op.drop_index(op.f("ix_strategy_signals_cycle_id"), table_name="strategy_signals")
    op.drop_index("ix_signals_strategy_created", table_name="strategy_signals")
    op.drop_table("strategy_signals")
    op.drop_index(op.f("ix_strategy_positions_strategy_id"), table_name="strategy_positions")
    op.drop_index(op.f("ix_strategy_positions_asset_id"), table_name="strategy_positions")
    op.drop_table("strategy_positions")
    op.drop_index(op.f("ix_strategy_allocations_strategy_id"), table_name="strategy_allocations")
    op.drop_table("strategy_allocations")
    op.drop_index("ix_price_asset_fetched", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_index("ix_psnap_strategy_taken", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_internal_crosses_cycle_id"), table_name="internal_crosses")
    op.drop_table("internal_crosses")
    op.drop_index(op.f("ix_execution_orders_cycle_id"), table_name="execution_orders")
    op.drop_table("execution_orders")
    op.drop_index(op.f("ix_asset_deployments_asset_id"), table_name="asset_deployments")
    op.drop_table("asset_deployments")
    op.drop_table("withdrawal_events")
    op.drop_index(op.f("ix_treasury_snapshots_taken_at"), table_name="treasury_snapshots")
    op.drop_table("treasury_snapshots")
    op.drop_table("system_state")
    op.drop_index(op.f("ix_system_events_type"), table_name="system_events")
    op.drop_index("ix_events_created", table_name="system_events")
    op.drop_table("system_events")
    op.drop_index(op.f("ix_strategies_code"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_table("simulated_balances")
    op.drop_index(op.f("ix_reconciliation_events_run_at"), table_name="reconciliation_events")
    op.drop_table("reconciliation_events")
    op.drop_index("ix_bars_symbol_date", table_name="historical_bars")
    op.drop_table("historical_bars")
    op.drop_table("funding_events")
    op.drop_index(op.f("ix_cycles_session_date"), table_name="cycles")
    op.drop_table("cycles")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
